name: Deploy to LAMP server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to LAMP server
        env:
          SSHPASS: "${{ secrets.SSH_PASSWORD }}"
        run: |
          sshpass -e rsync -avz --exclude='.git/' \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./ sonsite@lamp.ms.wits.ac.za:~/public_html/
      - name: Set permissions
        env:
          SSHPASS: "${{ secrets.SSH_PASSWORD }}"
        run: |
          sshpass -e ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            sonsite@lamp.ms.wits.ac.za \
            "chmod -R 755 ~/public_html"
