name: Deploy to LAMP server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies locally
        run: |
          echo "Installing dependencies locally..."
          npm ci || exit 1
          echo "Local dependencies installed successfully"

      - name: Deploy to LAMP server
        env:
          SSHPASS: "${{ secrets.SSH_PASSWORD }}"
        run: |
          echo "Starting deployment to LAMP server..."
          sshpass -e rsync -avz --exclude='.git/' --exclude='node_modules/' \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./ sonsite@lamp.ms.wits.ac.za:~/public_html/ || exit 1
          echo "Files deployed successfully"

      - name: Install dependencies on server and set permissions
        env:
          SSHPASS: "${{ secrets.SSH_PASSWORD }}"
        run: |
          echo "Installing dependencies and setting permissions on server..."
          sshpass -e ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            sonsite@lamp.ms.wits.ac.za \
            "cd ~/public_html && \
            echo 'Running npm install...' && \
            npm install && \
            echo 'Setting directory permissions...' && \
            chmod -R 755 . && \
            echo 'Setting file permissions...' && \
            find . -type f -exec chmod 644 {} + && \
            echo 'All operations completed successfully'" || exit 1
          echo "Server setup completed"
